export {default as About} from './Pro';
export {default as Agreement} from './Pro';
export {default as Articles} from './Articles';
export {default as Chat} from './Pro';
export {default as Components} from './Components';
export {default as Extras} from './Pro';
export {default as Home} from './Home';
export {default as Notifications} from './Pro';
export {default as NotificationsSettings} from './Pro';
export {default as Privacy} from './Pro';
export {default as Profile} from './Profile';
export {default as Register} from './Register';
export {default as Login} from './Pro';
export {default as Rental} from './Pro';
export {default as Rentals} from './Pro';
export {default as Booking} from './Pro';
export {default as Settings} from './Pro';
export {default as Shopping} from './Pro';
export {default as Pro} from './Pro';
export {default as QRScanner} from './QRScanner';
export {default as BlankTemplate} from './BlankTemplate';
export {default as QRInfo} from './QRInfo';
export {default as PhonePay} from './PhonePay';
export {default as UpiPay} from './UpiPay';
export {default as PrePayment} from './PrePayment'
export {default as PaymentOptions} from './PaymentOptions'
export {default as UserProfile} from './UserProfile'
export {default as CashBack} from './CashBack'
export {default as TransactionDetail} from './TransactionDetail'
export {default as Wallet } from './Wallet'
